# =======================================================================================
#
# Config
#
function gameConfig():
# =======================================================================================
# ---------------------------------------------------------------------------------------
#
    # バージョン情報
    set {ver} to "DevPreview-v2.1.0"
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # デフォルトゲームモード
    #---------
    # チーム戦
    set {Natto.defaultModeTeam} to false
    #---------
    # 紅白戦
    set {Natto.defaultMode2Team} to false
    #---------
    # だるま
    set {Natto.defaultModeDaruma} to false
    #---------
    # 雪合戦
    set {Natto.defaultModeYuki} to false
    # ---------
    # ibuibu Mode
    set {Natto.defaultModeIbuibu} to false
    # ---------
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 各チーム最大人数（３人以上はGUI非対応）
    set {Natto.teamMaxPlayer} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 開始前待機時間
    set {Natto.prepareTime} to 30
    set {Natto.countdownTimes} to 5
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # キルランキング表示順位数（上位〜位）
    set {Natto.KillRankingTimes} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # だるまモードでの被ダメージ量
    set {Natto.daruma.damage} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 回復薬での体力回復量
    #set {Natto.oniku.healAmount} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 一つのチェストから出るアイテム量（チェストインベントリーにおけるスロット占有量）
    set {Natto.maxChestSlotQua} to 10
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # ブロック設置後消えるまでの時間（秒）
    set {Natto.delBlockTime} to 60
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 雪合戦モードでブロックから出る雪玉の数（個）
    set {Natto.yukidamaAmount} to 1
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 雪合戦モードでの爆破威力
    set {Natto.snowball.power} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チェスト中身(モード：ノーマル)
    # その確率
#
    add 3 of apple to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
#
    add 2 of firework rocket to {Natto.chestItemName.normal::*}
    add 5 to {Natto.chestItemChance.normal::*}
#
    add 3 of emerald to {Natto.chestItemName.normal::*}
    add 5 to {Natto.chestItemChance.normal::*}
#
    add 3 of lapis lazuli to {Natto.chestItemName.normal::*}
    add 2 to {Natto.chestItemChance.normal::*}
#
    add 10 of experience bottle to {Natto.chestItemName.normal::*}
    add 3 to {Natto.chestItemChance.normal::*}
#
    add 2 of oak log to {Natto.chestItemName.normal::*}
    add 15 to {Natto.chestItemChance.normal::*}
#
    add 2 of stone to {Natto.chestItemName.normal::*}
    add 15 to {Natto.chestItemChance.normal::*}
#
    add 2 of string to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
#
    add 5 of arrow to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
#
    add 3 of leather to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
#
    add 3 of iron ingot to {Natto.chestItemName.normal::*}
    add 8 to {Natto.chestItemChance.normal::*}
#
    add 3 of gold ingot to {Natto.chestItemName.normal::*}
    add 5 to {Natto.chestItemChance.normal::*}
#
    add 1 of diamond to {Natto.chestItemName.normal::*}
    add 2 to {Natto.chestItemChance.normal::*}
#
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 販売価格
    #
    set {price.buy.leather} to 5
    set {price.buy.iron} to 15
    set {price.buy.gold} to 30
    set {price.buy.diamond} to 50

    set {price.buy.planks} to 5
    set {price.buy.stone} to 10
    set {price.buy.string} to 5
    set {price.buy.arrow} to 5

    set {price.buy.apple} to 5
    set {price.buy.firework} to 10
    set {price.buy.lapis} to 10
    set {price.buy.enchant} to 10

    #
    # 買取価格
    #

    set {price.sell.leather} to 1
    set {price.sell.iron} to 5
    set {price.sell.gold} to 10
    set {price.sell.diamond} to 20

    set {price.sell.planks} to 1
    set {price.sell.stone} to 5
    set {price.sell.string} to 1
    set {price.sell.arrow} to 1

    set {price.sell.apple} to 1
    set {price.sell.firework} to 5
    set {price.sell.lapis} to 5
    set {price.sell.enchant} to 5

    set {price.sell.leather_helmet} to 5
    set {price.sell.leather_chestplate} to 5
    set {price.sell.leather_leggings} to 5
    set {price.sell.leather_boots} to 5

    set {price.sell.iron_helmet} to 7
    set {price.sell.iron_chestplate} to 7
    set {price.sell.iron_leggings} to 7
    set {price.sell.iron_boots} to 7

    set {price.sell.golden_helmet} to 10
    set {price.sell.golden_chestplate} to 10
    set {price.sell.golden_leggings} to 10
    set {price.sell.golden_boots} to 10

    set {price.sell.diamond_helmet} to 20
    set {price.sell.diamond_chestplate} to 20
    set {price.sell.diamond_leggings} to 20
    set {price.sell.diamond_boots} to 20

    set {price.sell.wooden_sword} to 3
    set {price.sell.stone_sword} to 5
    set {price.sell.iron_sword} to 7
    set {price.sell.golden_sword} to 10

    set {price.sell.diamond_sword} to 20
    set {price.sell.bow} to 5
    set {price.sell.crossbow} to 10
    set {price.sell.elytra} to 5
#
# ---------------------------------------------------------------------------------------
#
    # デバッグモード
    set {debugMode} to false
#
# ---------------------------------------------------------------------------------------
