# ====================================================================================================================================================================================
#
# ===For Developer===   開発時のみ実行   ※ゲームが崩壊する可能性があるので決して実行しないこと※
#
# ====================================================================================================================================================================================

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# アスレ累計クリア回数をクリアします.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---asureclear:
    description:Clear asure clearcount
    permission:op
    permission message:You Don't have permission.
    trigger:
        loop all players:
            clear {asure.clearcount.%loop-player%}
        clear {asure.clearcount.%offline players%}




# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ロケーション変数を定義します.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---defineloca:
    description:define location variables
    permission:op
    permission message:You Don't have permission.
    trigger:
        if {defineloca} is false:
            set {defineloca} to true
            give a stick named "locaLobbySpawn" to player
            give a stick named "locaSky" to player
            give a stick named "locaDeathSpawn" to player
            give a golden hoe named "右クリックでチェスト座標を設定" with lore "クリックしたブロックのひとつ上にチェストが出るようになります" to player
            give a wooden hoe named "右クリックでチェスト座標を削除" to player
            message "&e&l>Dev &rロケーション変数定義モードに移行しました．離脱する場合は再度実行またはリロードしてください." to player
        else:
            set {defineloca} to false
            message "&e&l>Dev &rロケーション変数定義モードを終了しました．" to player

on right click:
    if event-item is stick named "locaLobbySpawn":
        if {defineloca} is true:
            cancel event
            set {Natto.locaLobbySpawn} to location of block above clicked block
            broadcast "&e&l>Dev &rlocaLobbySpawn を %{Natto.locaLobbySpawn}% に設定しました"

    if event-item is stick named "locaSky":
        if {defineloca} is true:
            cancel event
            set {Natto.locaSky} to location of block above clicked block
            broadcast "&e&l>Dev &rlocaSky を %{Natto.locaSky}% に設定しました"

    if event-item is stick named "locaDeathSpawn":
        if {defineloca} is true:
            cancel event
            set {Natto.locaDeathSpawn} to location of block above clicked block
            broadcast "&e&l>Dev &rlocaDeathSpawn を %{Natto.locaDeathSpawn}% に設定しました"

    if event-item is golden hoe named "右クリックでチェスト座標を設定" with lore "クリックしたブロックのひとつ上にチェストが出るようになります":
        if {defineloca} is true:
            cancel event
            add location of block above clicked block to {Natto.locaChest::*}
            broadcast "&e&l>Dev &r%location of block above clicked block% を {Natto.locaChest::*} に追加しました"

    if event-item is wooden hoe named "右クリックでチェスト座標を削除":
        if {defineloca} is true:
            cancel event
            remove location of block above clicked block from {Natto.locaChest::*}
            broadcast "&e&l>Dev &r%location of block above clicked block% を {Natto.locaChest::*} から削除しました"


# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# サーバーを開発モードに移行します.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---dev:
    description:Move to Development Mode
    permission:op
    permission message:You Don't have permission.
    trigger:
        broadcast "&e&l>Dev &r開発モードに移行します.終了する際はリロードしてください."
        execute console command "destroyable true"
        execute console command "gamerule sendCommandFeedback true"
        execute console command "gamerule reducedDebugInfo false"
        set {gameStatus} to 5
        loop all players:
            set loop-player's gamemode to creative


# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# チームをリセットします．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---teamgoodbye:
    description:Goodbye Team
    permission: skript.admin
    permission message:You Don't have permission.
    trigger:
        execute console command "scoreboard objectives remove admin"
        execute console command "scoreboard objectives remove red"
        execute console command "scoreboard objectives remove blue"
        execute console command "scoreboard objectives remove yellow"
        execute console command "scoreboard objectives remove green"
        execute console command "scoreboard objectives remove orange"
        execute console command "scoreboard objectives remove purple"
        execute console command "scoreboard objectives remove gray"
        execute console command "team remove admin"
        execute console command "team remove red"
        execute console command "team remove blue"
        execute console command "team remove yellow"
        execute console command "team remove green"
        execute console command "team remove orange"
        execute console command "team remove purple"
        execute console command "team remove gray"
        message "&e&l>Goodbye Team &r正常に実行されました" to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# LuckPermsにおける各権限グループのメンバーを表示します．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---rakutinlp-member:
    description:Show LuckPerms members
    permission:op
    permission message:You Don't have permission.
    trigger:
        make player execute command "/lp group skript.admin listmembers"
        make player execute command "/lp group player listmembers"
        message "&e[RakutinLP Member] &r正常に実行されました" to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# チーから離脱します．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---leaveteam:
    description:Leave Team
    permission:op
    permission message:You Don't have permission.
    trigger:
        teamLeave(player)