command /natto---asureclear:
    description:Clear asure clearcount
    permission:op
    permission message:You Don't have permission.
    trigger:
        loop all players:
            clear {asure.clearcount.%loop-player%}
        clear {asure.clearcount.%offline players%}
        message "&e&l>AsureClear &r正常に実行されました" to player and {admin::*}

command /natto---defineloca:
    description:define location variables
    permission:op
    permission message:You Don't have permission.
    trigger:
        if {defineloca} is false:
            set {defineloca} to true
            execute console command "destroyable true"
            set {debugMode} to true
            execute console command "gamerule sendCommandFeedback true"
            execute console command "gamerule reducedDebugInfo false"
            give a stick named "locaLobbySpawn" to player
            give a stick named "locaSky" to player
            give a stick named "locaDeathSpawn" to player
            give a golden hoe named "右クリックでチェスト座標を設定" with lore "クリックしたブロックのひとつ上にチェストが出るようになります" to player
            give a wooden hoe named "右クリックでチェスト座標を削除" to player
            message "&e&l>Dev &rロケーション変数定義モードに移行しました．終了する場合はリロードしてください." to player and {admin::*}
        else:
            set {defineloca} to false
            message "&e&l>Dev &r終了しました．" to player and {admin::*}

on right click:
    if event-item is stick named "locaLobbySpawn":
        if {defineloca} is true:
            cancel event
            set {Natto.locaLobbySpawn} to location of block above clicked block
            broadcast "&e&l>Dev &rlocaLobbySpawn を &e%{Natto.locaLobbySpawn}% &rに設定しました"

    if event-item is stick named "locaSky":
        if {defineloca} is true:
            cancel event
            set {Natto.locaSky} to location of block above clicked block
            broadcast "&e&l>Dev &rslocaSky を &e%{Natto.locaSky}% &rに設定しました"

    if event-item is stick named "locaDeathSpawn":
        if {defineloca} is true:
            cancel event
            set {Natto.locaDeathSpawn} to location of block above clicked block
            broadcast "&e&l>Dev &rlocaDeathSpawn を &e%{Natto.locaDeathSpawn}% &rに設定しました"

    if event-item is golden hoe named "右クリックでチェスト座標を設定" with lore "クリックしたブロックのひとつ上にチェストが出るようになります":
        if {defineloca} is true:
            if {Natto.locaChest::*} contain location of block above clicked block:
                cancel event
                message "&e&l>Dev &cError &r: すでに設定された座標です" to player
            else:
                cancel event
                add location of block above clicked block to {Natto.locaChest::*}
                set block above clicked block to chest
                broadcast "&e&l>Dev &rlocaChest に &e%location of block above clicked block% &rを追加しました"

    if event-item is wooden hoe named "右クリックでチェスト座標を削除":
        if {defineloca} is true:
            if {Natto.locaChest::*} contain location of block above clicked block:
                cancel event
                remove location of block above clicked block from {Natto.locaChest::*}
                set block above clicked block to air
                broadcast "&e&l>Dev &rlocaChest から &e%location of block above clicked block% &rを削除しました"
            else:
                cancel event
                message "&e&l>Dev &cError &r: リストに存在しない座標です" to player

command /natto---dev:
    description:Move to Development Mode
    permission:op
    permission message:You Don't have permission.
    trigger:
        broadcast "&e&l>Dev &rデバッグモードに移行します.終了する際はリロードしてください."
        execute console command "destroyable true"
        execute console command "gamerule sendCommandFeedback true"
        execute console command "gamerule reducedDebugInfo false"
        set {gameStatus} to 5
        set {debugMode} to true

command /natto---teamgoodbye:
    description:Goodbye Team
    permission: skript.admin
    permission message:You Don't have permission.
    trigger:
        execute console command "scoreboard objectives remove admin"
        execute console command "scoreboard objectives remove red"
        execute console command "scoreboard objectives remove blue"
        execute console command "scoreboard objectives remove yellow"
        execute console command "scoreboard objectives remove green"
        execute console command "scoreboard objectives remove orange"
        execute console command "scoreboard objectives remove purple"
        execute console command "scoreboard objectives remove black"
        execute console command "team remove admin"
        execute console command "team remove red"
        execute console command "team remove blue"
        execute console command "team remove yellow"
        execute console command "team remove green"
        execute console command "team remove orange"
        execute console command "team remove purple"
        execute console command "team remove black"
        message "&e&l>GoodbyeTeam &r正常に実行されました" to player and {admin::*}

command /natto---rakutinlp-member:
    description:Show LuckPerms members
    permission:op
    permission message:You Don't have permission.
    trigger:
        make player execute command "/lp group skript.admin listmembers"
        make player execute command "/lp group player listmembers"
        message "&e&l>RakutinLP-Member &r正常に実行されました" to player and {admin::*}

command /natto---leaveteam [<player>]:
    description:Leave Team
    permission:op
    permission message:You Don't have permission.
    trigger:
        if arg-1 is set:
            teamLeave(arg-1)
            message "&e&l>LeaveTeam &r正常に実行されました." to player and {admin::*}
            message "player:%arg-1%" to player and {admin::*}
        else:
            teamLeave(player)
            message "&e&l>LeaveTeam &r正常に実行されました." to player and {admin::*}
            message "player:%player%" to player and {admin::*}

command /natto---spawnchest:
    description:Spawn Chest
    permission:op
    permission message:You Don't have permission.
    trigger:
        spawnChest()
        message "&e&l>SpawnChest &r正常に実行されました." to player and {admin::*}