# ===================================================================================================================================================================================
# 開発用コマンド
# 基本使わないコマンド群 -> 頭にnattoつけて差別化　さらに--は使用頻度高，-は使用頻度低，-xx-はレガシー
# =====================================================================================================================================================================================


# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# それっぽい理由でサーバーを一時的にクローズします.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---asureclear:
    description:Clear asure clearcount
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        loop all players:
            clear {asure.clearcount.%loop-player%}
        clear {asure.clearcount.%offline players%}


# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# それっぽい理由でサーバーを一時的にクローズします.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---close:
    description:Close server
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        broadcast "&e[Dev] &rサーバーを一時的にクローズします.再開の際はリロードしてください."
        set {status} to 2



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# サーバーを開発モードに移行します.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---dev:
    description:Move to Development Mode
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        broadcast "&e[Dev] &r開発モードに移行します.終了する際はリロードしてください."
        execute console command "destroyable true"
        execute console command "gamerule sendCommandFeedback true"
        execute console command "gamerule reducedDebugInfo false"
        set {status} to 0
        loop all players:
            set loop-player's gamemode to creative



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ユーザーを監視モードに移行します.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---monitor:
    description:Move to Monitor Mode for debug
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        if {status} is 1:
            if {admin.%player%} is "true":
                set {sidebar.%player%} to 9
                message "&e[Dev] &r監視モードに移行しました"
        else:
            message "&e[Dev] &r現在監視モードに移行することはできません"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# LuckPermsにおける各権限グループのメンバーを表示します．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---rakutinlp-member:
    description:Show LuckPerms members
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        make player execute command "/lp group skript.admin listmembers"
        make player execute command "/lp group player listmembers"
        message "&e[RakutinLP Member] &r正常に実行されました" to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ゲームをリペアーします.（たぶんバグる）
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---repair-suviver <number>:
    description:Repair {surviver}
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        set {surviver} to arg-1
        message "&e[Dev] &r{surviver}を%arg-1%に設定しました"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# チームをリセットします．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto---teamgoodbye:
    description:Goodbye Team
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        execute console command "scoreboard objectives remove admin"
        execute console command "scoreboard objectives remove red"
        execute console command "scoreboard objectives remove blue"
        execute console command "scoreboard objectives remove yellow"
        execute console command "scoreboard objectives remove green"
        execute console command "scoreboard objectives remove orange"
        execute console command "scoreboard objectives remove purple"
        execute console command "scoreboard objectives remove gray"
        execute console command "team remove admin"
        execute console command "team remove red"
        execute console command "team remove blue"
        execute console command "team remove yellow"
        execute console command "team remove green"
        execute console command "team remove orange"
        execute console command "team remove purple"
        execute console command "team remove gray"
        message "&e[Goodbye Team] &r正常に実行されました" to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 生者の気分を味わいます.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto--ikiru:
    description:Make player to Alive Player
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        set {sidebar.%player%} to 1



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 敗者の気分を味わいます.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto--kuyasii:
    description:Make player to Dead Player
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        set {sidebar.%player%} to 2



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 1位の気分を味わいます.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto--uresii:
    description:Make player to First Rank Player
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        set {sidebar.%player%} to 3



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# デバッグモードの切替をします．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto-debugmode <text>:
    description:Switch Debug Mode
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        if arg-1 is "true":
            set {debugMode} to "true"
        if arg-1 is "false":
            set {debugMode} to "false"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# LuckPermsの初期設定を行います．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto-rakutinlp:
    description:Create group on LuckPerms
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        execute console command "lp user ShimaShima_710 permission set luckperms.*"
        make player execute command "/lp creategroup player"
        make player execute command "/lp creategroup skript.admin"
        make player execute command "/lp group skript.admin permission set skript.* true"
        make player execute command "/lp user ShimaShima_710 parent add skript.admin"
        message "&e[RakutinLP] &r正常に実行されました" to player









# =====================================================================================================================================================================================
# ===Legacy System===  すでに更新を終えているため動作はサポートされません
# =====================================================================================================================================================================================

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 変数・スコアのリセットをします．現在はリロードに組み込んであるので不要です．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto-xx-debug:
    description:Reset variable via Skript and scores via Datapack
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        make player execute command "/admin leave"
        set {surviver} to 0
        set {qua.admin} to 0
        set {qua.player} to 0
        execute console command "function shimashima:01_replay"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# CoreProtectでワールドのロールバックをします．動きませんでしたがは
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /natto-xx-reset:
    description:Test for CoreProtect *not adopted
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        loop all players:
            execute console command "co rollback time: 1d radius: ##world user:%loop-player%"