# ====================================================================================================================================================================================
# 一般コマンド
# 通常利用で実行可能性のあるコマンド群
# =====================================================================================================================================================================================


# =====================================================================================================================================================================================
#
# ===For User===   全ユーザーが実行可能
#
# =====================================================================================================================================================================================
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# サイドバーのリセットをします．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /sidebar:
    description:Wipe sidebar
    trigger:
        if {sidebar.%player%} is 0:
            set {sidebar.%player%} to 0
        if {sidebar.%player%} is 1:
            set {sidebar.%player%} to 1
        if {sidebar.%player%} is 2:
            set {sidebar.%player%} to 2
        if {sidebar.%player%} is 9:
            set {sidebar.%player%} to 9
        message "&b[システム] &rサイドバーをリフレッシュしました" to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# バージョン情報を提示します
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /ver:
    description:Show version now working
    trigger:
        message "&b[システム] &r現在のバージョンは &c%{ver}% &rです" to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ゲーム中に意図的に全体チャットを使用します。
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /z <text>:
    description:ZE-NN-TYA
    trigger:
        broadcast "&7[-ZENNTYA-] &r<%player%> %arg-1%"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# プレイヤーヘッドとチェストがもらえます。
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /rirogu:
    description:Give Player Head and Chest.
    trigger:
        if {status} is not 1:
            set slot 4 of player's inventory to 1 of skull of player named "&d右クリックでチェックポイントへTP"
            set slot 8 of player's inventory to a chest named "&dチーム選択"
            play sound "block.note_block.bell" to player
        else:
            broadcast "&b[システム] &r現在利用できません"
            play sound "block.note_block.banjo" to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 謎解きの回答を送信します。
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /answer <text>:
    description:Answer question.
    trigger:
        if {count.ans.%player%} is 0:
            add 1 to {count.ans.%player%}
            if arg-1 is "0":
                broadcast "&6[謎解き] &r%player% が謎解きをクリアしました！！おめでとう！！！！"
                play sound "ui.toast.challenge_complete" to player
            else:
                message "&6[謎解き] &r残念不正解..." to player
                play sound "entity.villager.no" to player
        else:
            message "&6[謎解き] &r回答出来るのは一試合につき一回までです" to player
            play sound "block.note_block.banjo" to player





# =====================================================================================================================================================================================
#
# ===For Game Master===   OP保持者もしくはadmin経験者(LP権限グループ"Skript.admin")のみ実行可能
#
# =====================================================================================================================================================================================
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# adminに入ったり出たりします．adminは変数{admin.%player%}またはチーム"admin"で判別．一度でもadminになればLP権限グループ"skript.admin"に追加され，OP出なくともコマンドの実行は可能になります
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /admin [<text>] [<player>]:
    description:Make specific user to admin
    permission: skript.admin
    permission message:Admin専用コマンドです。
    usage:/admin <join/leave> [<プレイヤー>] ※プレイヤー未指定の場合は自身を操作します
    aliases:/ad
    trigger:
        if arg-1 is "join":
            if arg-2 is set:
                if {admin.%arg-2%} is "true":
                    message "&b[admin] &r%arg-2%はすでにadminです" to player
                else:
                    execute console command "op %arg-2%"
                    make player execute command "/gamemode creative %arg-2%"
                    make arg-2 execute command "natto---leaveteam"
                    make player execute command "/team join admin %arg-2%"
                    make arg-2 execute command "/book"
                    execute console command "lp user %arg-2% parent add skript.admin"
                    message "&b[admin] &r%arg-2%をAdminに追加しました。" to player
                    message "&b[admin] &r%player%があなたをAdminに追加しました。" to arg-2
                    set {admin.%arg-2%} to "true"
                    set the arg-2's chat name to "&4%name of arg-2%"
                    set the arg-2's display name to "&4[運営] %name of arg-2%"
                    execute console command "scoreboard players reset {qua.admin}：%{qua.admin}%人 admin"
                    add 1 to {qua.admin}
                    execute console command "scoreboard players set {qua.admin}：%{qua.admin}%人 admin -6"
                    add player to {team.admin::*}
                    set {team.joined.%arg-2%} to "true"
            if arg-2 is not set:
                if {admin.%player%} is "true":
                    message "&b[admin] &rあなたはすでにadminです" to player
                else:
                    execute console command "op %player%"
                    make player execute command "/gamemode creative %player%"
                    make player execute command "natto---leaveteam"
                    make player execute command "/team join admin %player%"
                    make player execute command "/book"
                    execute console command "lp user %player% parent add skript.admin"
                    message "&b[admin] &r%player%をAdminに追加しました。" to player
                    set {admin.%player%} to "true"
                    set the player's chat name to "&4%name of player%"
                    set the player's display name to "&4[運営] %name of player%"
                    execute console command "scoreboard players reset {qua.admin}：%{qua.admin}%人 admin"
                    add 1 to {qua.admin}
                    execute console command "scoreboard players set {qua.admin}：%{qua.admin}%人 admin -6"
                    set {team.joined.%player%} to "true"
        if arg-1 is "leave":
            if arg-2 is set:
                if {admin.%arg-2%} is "false":
                    message "&b[admin] &r%arg-2%はすでにadminではありません" to player
                else:
                    make player execute command "/gamemode adventure %arg-2%"
                    make player execute command "/effect clear %arg-2% minecraft:night_vision"
                    make player execute command "/team leave %arg-2%"
                    message "&b[admin] &r%arg-2%をAdminから除外しました。" to player
                    message "&b[admin] &r%player%があなたをAdminから除外しました。" to arg-2
                    set {admin.%arg-2%} to "false"
                    set the arg-2's chat name to name of arg-2
                    set the arg-2's display name to name of arg-2
                    execute console command "scoreboard players reset {qua.admin}：%{qua.admin}%人 admin"
                    reduce {qua.admin} by 1
                    execute console command "scoreboard players set {qua.admin}：%{qua.admin}%人 admin -6"
                    make arg-2 execute command "natto---leaveteam"
                    set {team.joined.%arg-2%} to "false"
            if arg-2 is not set:
                if {admin.%player%} is "false":
                    message "&b[admin] &rあなたはすでにadminではありません" to player
                else:
                    make player execute command "/gamemode adventure %player%"
                    make player execute command "/effect clear @s minecraft:night_vision"
                    make player execute command "/team leave %player%"
                    message "&b[admin] &r%player%をAdminから除外しました。" to player
                    set {admin.%player%} to "false"
                    set the player's chat name to name of player
                    set the player's display name to name of player
                    execute console command "scoreboard players reset {qua.admin}：%{qua.admin}%人 admin"
                    reduce {qua.admin} by 1
                    execute console command "scoreboard players set {qua.admin}：%{qua.admin}%人 admin -6"
                    make player execute command "natto---leaveteam"
                    set {team.joined.%player%} to "false"
        if arg-1 is not set:
            if {admin.%player%} is "true":
                make player execute command "/gamemode adventure %player%"
                make player execute command "/effect clear @s minecraft:night_vision"
                make player execute command "/team leave %player%"
                message "&b[admin] &r%player%をAdminから除外しました。" to player
                set {admin.%player%} to "false"
                set the player's chat name to name of player
                set the player's display name to name of player
                execute console command "scoreboard players reset {qua.admin}：%{qua.admin}%人 admin"
                reduce {qua.admin} by 1
                execute console command "scoreboard players set {qua.admin}：%{qua.admin}%人 admin -6"
                make player execute command "natto---leaveteam"
                set {team.joined.%player%} to "false"
                stop
            if {admin.%player%} is "false":
                execute console command "op %player%"
                make player execute command "/gamemode creative %player%"
                make player execute command "natto---leaveteam"
                make player execute command "/team join admin %player%"
                make player execute command "/book"
                execute console command "lp user %player% parent add skript.admin"
                message "&b[admin] &r%player%をAdminに追加しました。" to player
                set {admin.%player%} to "true"
                set the player's chat name to "&4%name of player%"
                set the player's display name to "&4[運営] %name of player%"
                execute console command "scoreboard players reset {qua.admin}：%{qua.admin}%人 admin"
                add 1 to {qua.admin}
                execute console command "scoreboard players set {qua.admin}：%{qua.admin}%人 admin -6"
                set {team.joined.%player%} to "true"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# チームに入ります。一般ユーザーのチームの出入りはこのコマンドに依存します。
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /join <text> <player>:
    description:Join Team
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        if arg-1 is "red":
            if {team.which.%arg-2%} is "red":
                play sound "block.note_block.banjo" to arg-2
                message "&b[システム] &rあなたはすでにそのチームに所属しています！" to arg-2
                stop
            if {team.which.%arg-2%} is "blue":
                reduce {qua.team.blue} by 1
                remove arg-2 from {team.blue::*}
                execute console command "scoreboard players reset %name of arg-2% blue"
            if {team.which.%arg-2%} is "yellow":
                reduce {qua.team.yellow} by 1
                remove arg-2 from {team.yellow::*}
                execute console command "scoreboard players reset %name of arg-2% yellow"
            if {team.which.%arg-2%} is "green":
                reduce {qua.team.green} by 1
                remove arg-2 from {team.green::*}
                execute console command "scoreboard players reset %name of arg-2% green"
            if {team.which.%arg-2%} is "orange":
                reduce {qua.team.orange} by 1
                remove arg-2 from {team.orange::*}
                execute console command "scoreboard players reset %name of arg-2% orange"
            if {team.which.%arg-2%} is "purple":
                reduce {qua.team.purple} by 1
                remove arg-2 from {team.purple::*}
                execute console command "scoreboard players reset %name of arg-2% purple"
            if {team.which.%arg-2%} is "gray":
                reduce {qua.team.gray} by 1
                remove arg-2 from {team.gray::*}
                execute console command "scoreboard players reset %name of arg-2% gray"
            if {admin.%arg-2%} is "true":
                make arg-2 execute command "admin leave"
            add arg-2 to {team.red::*}
            set {team.which.%arg-2%} to "red"
            add 1 to {qua.team.red}
            set {team.joined.%arg-2%} to "true"
            set the arg-2's display name to "&c[Red] &r%name of arg-2%"
            execute console command "scoreboard players set %name of arg-2% red 1"
            execute console command "team join red %arg-2%"
            play sound "entity.player.levelup" to arg-2
            message "&b[システム] &r赤チームに入りました！" to arg-2

        if arg-1 is "blue":
            if {team.which.%arg-2%} is "blue":
                play sound "block.note_block.banjo" to arg-2
                message "&b[システム] &rあなたはすでにそのチームに所属しています！" to arg-2
                stop
            if {team.which.%arg-2%} is "red":
                reduce {qua.team.red} by 1
                remove arg-2 from {team.red::*}
                execute console command "scoreboard players reset %name of arg-2% red"
            if {team.which.%arg-2%} is "yellow":
                reduce {qua.team.yellow} by 1
                remove arg-2 from {team.yellow::*}
                execute console command "scoreboard players reset %name of arg-2% yellow"
            if {team.which.%arg-2%} is "green":
                reduce {qua.team.green} by 1
                remove arg-2 from {team.green::*}
                execute console command "scoreboard players reset %name of arg-2% green"
            if {team.which.%arg-2%} is "orange":
                reduce {qua.team.orange} by 1
                remove arg-2 from {team.orange::*}
                execute console command "scoreboard players reset %name of arg-2% orange"
            if {team.which.%arg-2%} is "purple":
                reduce {qua.team.purple} by 1
                remove arg-2 from {team.purple::*}
                execute console command "scoreboard players reset %name of arg-2% purple"
            if {team.which.%arg-2%} is "gray":
                reduce {qua.team.gray} by 1
                remove arg-2 from {team.gray::*}
                execute console command "scoreboard players reset %name of arg-2% gray"
            if {admin.%arg-2%} is "true":
                make arg-2 execute command "admin leave"
            add arg-2 to {team.blue::*}
            set {team.which.%arg-2%} to "blue"
            add 1 to {qua.team.blue}
            set {team.joined.%arg-2%} to "true"
            set the arg-2's display name to "&9[Blue] &r%name of arg-2%"
            execute console command "scoreboard players set %name of arg-2% blue 1"
            execute console command "team join blue %arg-2%"
            play sound "entity.player.levelup" to arg-2
            message "&b[システム] &r青チームに入りました！" to arg-2

        if arg-1 is "yellow":
            if {team.which.%arg-2%} is "yellow":
                play sound "block.note_block.banjo" to arg-2
                message "&b[システム] &rあなたはすでにそのチームに所属しています！" to arg-2
                stop
            if {team.which.%arg-2%} is "blue":
                reduce {qua.team.blue} by 1
                remove arg-2 from {team.blue::*}
                execute console command "scoreboard players reset %name of arg-2% blue"
            if {team.which.%arg-2%} is "red":
                reduce {qua.team.red} by 1
                remove arg-2 from {team.red::*}
                execute console command "scoreboard players reset %name of arg-2% red"
            if {team.which.%arg-2%} is "green":
                reduce {qua.team.green} by 1
                remove arg-2 from {team.green::*}
                execute console command "scoreboard players reset %name of arg-2% green"
            if {team.which.%arg-2%} is "orange":
                reduce {qua.team.orange} by 1
                remove arg-2 from {team.orange::*}
                execute console command "scoreboard players reset %name of arg-2% orange"
            if {team.which.%arg-2%} is "purple":
                reduce {qua.team.purple} by 1
                remove arg-2 from {team.purple::*}
                execute console command "scoreboard players reset %name of arg-2% purple"
            if {team.which.%arg-2%} is "gray":
                reduce {qua.team.gray} by 1
                remove arg-2 from {team.gray::*}
                execute console command "scoreboard players reset %name of arg-2% gray"
            if {admin.%arg-2%} is "true":
                make arg-2 execute command "admin leave"
            add arg-2 to {team.yellow::*}
            set {team.which.%arg-2%} to "yellow"
            add 1 to {qua.team.yellow}
            set {team.joined.%arg-2%} to "true"
            set the arg-2's display name to "&e[Yellow] &r%name of arg-2%"
            execute console command "scoreboard players set %name of arg-2% yellow 1"
            execute console command "team join yellow %arg-2%"
            play sound "entity.player.levelup" to arg-2
            message "&b[システム] &r黄色チームに入りました！" to arg-2

        if arg-1 is "green":
            if {team.which.%arg-2%} is "green":
                play sound "block.note_block.banjo" to arg-2
                message "&b[システム] &rあなたはすでにそのチームに所属しています！" to arg-2
                stop
            if {team.which.%arg-2%} is "blue":
                reduce {qua.team.blue} by 1
                remove arg-2 from {team.blue::*}
                execute console command "scoreboard players reset %name of arg-2% blue"
            if {team.which.%arg-2%} is "yellow":
                reduce {qua.team.yellow} by 1
                remove arg-2 from {team.yellow::*}
                execute console command "scoreboard players reset %name of arg-2% yellow"
            if {team.which.%arg-2%} is "red":
                reduce {qua.team.red} by 1
                remove arg-2 from {team.red::*}
                execute console command "scoreboard players reset %name of arg-2% red"
            if {team.which.%arg-2%} is "orange":
                reduce {qua.team.orange} by 1
                remove arg-2 from {team.orange::*}
                execute console command "scoreboard players reset %name of arg-2% orange"
            if {team.which.%arg-2%} is "purple":
                reduce {qua.team.purple} by 1
                remove arg-2 from {team.purple::*}
                execute console command "scoreboard players reset %name of arg-2% purple"
            if {team.which.%arg-2%} is "gray":
                reduce {qua.team.gray} by 1
                remove arg-2 from {team.gray::*}
                execute console command "scoreboard players reset %name of arg-2% gray"
            if {admin.%arg-2%} is "true":
                make arg-2 execute command "admin leave"
            add arg-2 to {team.green::*}
            set {team.which.%arg-2%} to "green"
            add 1 to {qua.team.green}
            set {team.joined.%arg-2%} to "true"
            set the arg-2's display name to "&a[Green] &r%name of arg-2%"
            execute console command "scoreboard players set %name of arg-2% green 1"
            execute console command "team join green %arg-2%"
            play sound "entity.player.levelup" to arg-2
            message "&b[システム] &r緑チームに入りました！" to arg-2

        if arg-1 is "orange":
            if {team.which.%arg-2%} is "orange":
                play sound "block.note_block.banjo" to arg-2
                message "&b[システム] &rあなたはすでにそのチームに所属しています！" to arg-2
                stop
            if {team.which.%arg-2%} is "blue":
                reduce {qua.team.blue} by 1
                remove arg-2 from {team.blue::*}
                execute console command "scoreboard players reset %name of arg-2% blue"
            if {team.which.%arg-2%} is "yellow":
                reduce {qua.team.yellow} by 1
                remove arg-2 from {team.yellow::*}
                execute console command "scoreboard players reset %name of arg-2% yellow"
            if {team.which.%arg-2%} is "green":
                reduce {qua.team.green} by 1
                remove arg-2 from {team.green::*}
                execute console command "scoreboard players reset %name of arg-2% green"
            if {team.which.%arg-2%} is "red":
                reduce {qua.team.red} by 1
                remove arg-2 from {team.red::*}
                execute console command "scoreboard players reset %name of arg-2% red"
            if {team.which.%arg-2%} is "purple":
                reduce {qua.team.purple} by 1
                remove arg-2 from {team.purple::*}
                execute console command "scoreboard players reset %name of arg-2% purple"
            if {team.which.%arg-2%} is "gray":
                reduce {qua.team.gray} by 1
                remove arg-2 from {team.gray::*}
                execute console command "scoreboard players reset %name of arg-2% gray"
            if {admin.%arg-2%} is "true":
                make arg-2 execute command "admin leave"
            add arg-2 to {team.orange::*}
            set {team.which.%arg-2%} to "orange"
            add 1 to {qua.team.orange}
            set {team.joined.%arg-2%} to "true"
            set the arg-2's display name to "&6[Orange] &r%name of arg-2%"
            execute console command "scoreboard players set %name of arg-2% orange 1"
            execute console command "team join orange %arg-2%"
            play sound "entity.player.levelup" to arg-2
            message "&b[システム] &rオレンジチームに入りました！" to arg-2

        if arg-1 is "purple":
            if {team.which.%arg-2%} is "purple":
                play sound "block.note_block.banjo" to arg-2
                message "&b[システム] &rあなたはすでにそのチームに所属しています！" to arg-2
                stop
            if {team.which.%arg-2%} is "blue":
                reduce {qua.team.blue} by 1
                remove arg-2 from {team.blue::*}
                execute console command "scoreboard players reset %name of arg-2% blue"
            if {team.which.%arg-2%} is "yellow":
                reduce {qua.team.yellow} by 1
                remove arg-2 from {team.yellow::*}
                execute console command "scoreboard players reset %name of arg-2% yellow"
            if {team.which.%arg-2%} is "green":
                reduce {qua.team.green} by 1
                remove arg-2 from {team.green::*}
                execute console command "scoreboard players reset %name of arg-2% green"
            if {team.which.%arg-2%} is "orange":
                reduce {qua.team.orange} by 1
                remove arg-2 from {team.orange::*}
                execute console command "scoreboard players reset %name of arg-2% orange"
            if {team.which.%arg-2%} is "red":
                reduce {qua.team.red} by 1
                remove arg-2 from {team.red::*}
                execute console command "scoreboard players reset %name of arg-2% red"
            if {team.which.%arg-2%} is "gray":
                reduce {qua.team.gray} by 1
                remove arg-2 from {team.gray::*}
                execute console command "scoreboard players reset %name of arg-2% gray"
            if {admin.%arg-2%} is "true":
                make arg-2 execute command "admin leave"
            add arg-2 to {team.purple::*}
            set {team.which.%arg-2%} to "purple"
            add 1 to {qua.team.purple}
            set {team.joined.%arg-2%} to "true"
            set the arg-2's display name to "&d[Purple] &r%name of arg-2%"
            execute console command "scoreboard players set %name of arg-2% purple 1"
            execute console command "team join purple %arg-2%"
            play sound "entity.player.levelup" to arg-2
            message "&b[システム] &r紫チームに入りました！" to arg-2

        if arg-1 is "gray":
            if {team.which.%arg-2%} is "gray":
                play sound "block.note_block.banjo" to arg-2
                message "&b[システム] &rあなたはすでにそのチームに所属しています！" to arg-2
                stop
            if {team.which.%arg-2%} is "blue":
                reduce {qua.team.blue} by 1
                remove arg-2 from {team.blue::*}
                execute console command "scoreboard players reset %name of arg-2% blue"
            if {team.which.%arg-2%} is "yellow":
                reduce {qua.team.yellow} by 1
                remove arg-2 from {team.yellow::*}
                execute console command "scoreboard players reset %name of arg-2% yellow"
            if {team.which.%arg-2%} is "green":
                reduce {qua.team.green} by 1
                remove arg-2 from {team.green::*}
                execute console command "scoreboard players reset %name of arg-2% green"
            if {team.which.%arg-2%} is "orange":
                reduce {qua.team.orange} by 1
                remove arg-2 from {team.orange::*}
                execute console command "scoreboard players reset %name of arg-2% orange"
            if {team.which.%arg-2%} is "purple":
                reduce {qua.team.purple} by 1
                remove arg-2 from {team.purple::*}
                execute console command "scoreboard players reset %name of arg-2% purple"
            if {team.which.%arg-2%} is "red":
                reduce {qua.team.red} by 1
                remove arg-2 from {team.red::*}
                execute console command "scoreboard players reset %name of arg-2% red"
            if {admin.%arg-2%} is "true":
                make arg-2 execute command "admin leave"
            add arg-2 to {team.gray::*}
            set {team.which.%arg-2%} to "gray"
            add 1 to {qua.team.gray}
            set {team.joined.%arg-2%} to "true"
            set the arg-2's display name to "&7[Gray] &r%name of arg-2%"
            execute console command "scoreboard players set %name of arg-2% gray 1"
            execute console command "team join gray %arg-2%"
            play sound "entity.player.levelup" to arg-2
            message "&b[システム] &rグレーチームに入りました！" to arg-2



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# admin権限でプレイヤーを復活させます。一般ユーザーによる復活はこのコマンドに依存しません。
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /revival:
    description:Revival Someone
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        open chest inventory with 5 row named "&0復活させる人を選んでください" to player
        set slot 1 of player's current inventory to red wool named "&lRed Team"
        set slot 10 of player's current inventory to skull of {team.red::1} named "&l%{team.red::1}% &rを復活"
        set slot 19 of player's current inventory to skull of {team.red::2} named "&l%{team.red::2}% &rを復活"
        set slot 28 of player's current inventory to skull of {team.red::3} named "&l%{team.red::3}% &rを復活"
        set slot 37 of player's current inventory to red wool named "&lRed Team"

        set slot 2 of player's current inventory to blue wool named "&lBlue Team"
        set slot 11 of player's current inventory to skull of {team.blue::1} named "&l%{team.blue::1}% &rを復活"
        set slot 20 of player's current inventory to skull of {team.blue::2} named "&l%{team.blue::2}% &rを復活"
        set slot 29 of player's current inventory to skull of {team.blue::3} named "&l%{team.blue::3}% &rを復活"
        set slot 38 of player's current inventory to blue wool named "&lBlue Team"

        set slot 3 of player's current inventory to yellow wool named "&lYellow Team"
        set slot 12 of player's current inventory to skull of {team.yellow::1} named "&l%{team.yellow::1}% &rを復活"
        set slot 21 of player's current inventory to skull of {team.yellow::2} named "&l%{team.yellow::2}% &rを復活"
        set slot 30 of player's current inventory to skull of {team.yellow::3} named "&l%{team.yellow::3}% &rを復活"
        set slot 39 of player's current inventory to yellow wool named "&lYellow Team"

        set slot 4 of player's current inventory to green wool named "&lGreen Team"
        set slot 13 of player's current inventory to skull of {team.green::1} named "&l%{team.green::1}% &rを復活"
        set slot 22 of player's current inventory to skull of {team.green::2} named "&l%{team.green::2}% &rを復活"
        set slot 31 of player's current inventory to skull of {team.green::3} named "&l%{team.green::3}% &rを復活"
        set slot 40 of player's current inventory to green wool named "&lGreen Team"

        set slot 5 of player's current inventory to orange wool named "&lOrange Team"
        set slot 14 of player's current inventory to skull of {team.orange::1} named "&l%{team.orange::1}% &rを復活"
        set slot 23 of player's current inventory to skull of {team.orange::2} named "&l%{team.orange::2}% &rを復活"
        set slot 32 of player's current inventory to skull of {team.orange::3} named "&l%{team.orange::3}% &rを復活"
        set slot 41 of player's current inventory to orange wool named "&lOrange Team"

        set slot 6 of player's current inventory to purple wool named "&lPurple Team"
        set slot 15 of player's current inventory to skull of {team.purple::1} named "&l%{team.purple::1}% &rを復活"
        set slot 24 of player's current inventory to skull of {team.purple::2} named "&l%{team.purple::2}% &rを復活"
        set slot 33 of player's current inventory to skull of {team.purple::3} named "&l%{team.purple::3}% &rを復活"
        set slot 42 of player's current inventory to purple wool named "&lPurple Team"

        set slot 7 of player's current inventory to gray wool named "&lGray Team"
        set slot 16 of player's current inventory to skull of {team.gray::1} named "&l%{team.gray::1}% &rを復活"
        set slot 25 of player's current inventory to skull of {team.gray::2} named "&l%{team.gray::2}% &rを復活"
        set slot 34 of player's current inventory to skull of {team.gray::3} named "&l%{team.gray::3}% &rを復活"
        set slot 43 of player's current inventory to gray wool named "&lGray Team"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# スキルに関するコマンドです。arg-1がchoiseでスキル選択画面を開きます。一般ユーザーによるスキル選択はこのコマンドに依存します。
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /skill <text> <player>:
    description:Skill Command.
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        if arg-1 is "choise":
            set {skill.openingchest.%arg-2%} to "true"
            open chest inventory with 2 row named "&0スキルを選んでください" to arg-2
            set slot 1 of arg-2's current inventory to red dye named "スキル1"
            set slot 2 of arg-2's current inventory to lapis lazuli named " "
            set slot 3 of arg-2's current inventory to yellow dye named " "
            set slot 4 of arg-2's current inventory to green dye named " "
            set slot 5 of arg-2's current inventory to orange dye named " "
            set slot 6 of arg-2's current inventory to bone meal named " "
            set slot 7 of arg-2's current inventory to gray stained glass pane named "キャンセルする"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 掘削の可否を設定します
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /destroyable [<text>]:
    description:Define destroyable
    permission: skript.admin
    permission message:Admin専用コマンドです。
    aliases:/des
    trigger:
        if arg-1 is "true":
            set {destroyable} to "true"
            broadcast "&b[運営] &rブロックの破壊が可能になりました"
        if arg-1 is "false":
            set {destroyable} to "false"
            broadcast "&b[運営] &rブロックの破壊が不可能になりました"
        if arg-1 is not set:
            if {destroyable} is "false":
                set {destroyable} to "true"
                broadcast "&b[運営] &rブロックの破壊が可能になりました"
                stop
            if {destroyable} is "true":
                set {destroyable} to "false"
                broadcast "&b[運営] &rブロックの破壊が不可能になりました"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 安地の範囲を設定しなおします．これはゲーム開始後に設定する場合のコマンドです．*速度の設定は必須です
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /anntirange <number> <number>:
    description:Define SafeZone range and speed
    permission: skript.admin
    permission message:Admin専用コマンドです。
    usage:/anntirange <範囲> <速度> ※速度の値は最終安地までの残り時間に同じ
    trigger:
        execute console command "worldborder set %arg-1%"
        broadcast "&b[運営] &r安地のサイズを%arg-1%に変更しました"
        execute console command "worldborder set 10 %arg-2%"
        broadcast "&b[運営] &r収縮完了までの時間を%arg-2%に変更しました"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 安地の収縮スピードのみを設定しなおします．範囲は現在の状態のまま進行します．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /anntispeed <number>:
    description:Define SafeZone speed
    permission: skript.admin
    permission message:Admin専用コマンドです。
    usage:/speed <速度> ※速度の値は最終安地までの残り時間に同じ
    trigger:
        execute console command "worldborder set 10 %arg-1%"
        broadcast "&b[運営] &r収縮完了までの時間を%arg-1%に変更しました"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Mode Change
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /mode <text>:
    description:Switch Mode
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        if arg-1 is "ibuibu":
            if {mode.ibuibu} is "true":
                set {mode.ibuibu} to "false"
                execute console command "scoreboard players set ibuibumode ibuibumode 0"
                broadcast "&b[運営] &r「ibuibu Mode」がオフになりました"
            else:
                set {mode.ibuibu} to "true"
                execute console command "scoreboard players set ibuibumode ibuibumode 1"
                broadcast "&b[運営] &r「ibuibu Mode」がオンになりました"

        if arg-1 is "daruma":
            if {mode.daruma} is "true":
                set {mode.daruma} to "false"
                broadcast "&b[運営] &r「だるまさんが転んだモード」がオフになりました"
                stop
            else:
                set {mode.daruma} to "true"
                broadcast "&b[運営] &r「だるまさんが転んだモード」がオンになりました"

        if arg-1 is "yumi":
            if {mode.yumi} is "true":
                set {mode.yumi} to "false"
                execute console command "datapack disable ""file/ibuibu-yumi-"""
                execute console command "datapack enable ""file/ibuibu"""
                broadcast "&b[運営] &r「武器制限モード-弓のみ-」がオフになりました"
                stop
            else:
                set {mode.yumi} to "true"
                if {mode.yukidama} is "true":
                    set {mode.yukidama} to "false"
                    execute console command "datapack disable ""file/ibuibu-yukidama-"""
                    broadcast "&b[運営] &r「武器制限モード-雪玉のみ-」がオフになりました"
                execute console command "datapack disable ""file/ibuibu"""
                execute console command "datapack enable ""file/ibuibu-yumi-"""
                broadcast "&b[運営] &r「武器制限モード-弓のみ-」がオンになりました"

        if arg-1 is "yukidama":
            if {mode.yukidama} is "true":
                set {mode.yukidama} to "false"
                execute console command "datapack disable ""file/ibuibu-yukidama-"""
                execute console command "datapack enable ""file/ibuibu"""
                broadcast "&b[運営] &r「武器制限モード-雪玉のみ-」がオフになりました"
                stop
            else:
                set {mode.yukidama} to "true"
                if {mode.yumi} is "true":
                    set {mode.yumi} to "false"
                    execute console command "datapack disable ""file/ibuibu-yumi-"""
                    execute console command "datapack enable ""file/ibuibu"""
                    broadcast "&b[運営] &r「武器制限モード-弓のみ-」がオフになりました"
                execute console command "datapack disable ""file/ibuibu"""
                execute console command "datapack enable ""file/ibuibu-yukidama-"""
                broadcast "&b[運営] &r「武器制限モード-雪玉のみ-」がオンになりました"




# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 本を渡します．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /book:
    description:Give ibuibuBook
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        make player execute command "function shimashima:02_admin-book"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 村人のスポーンエッグを渡します．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /murabito:
    description:Give Villager's SpawnEgg
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        make player execute command "function shimashima:02_murabito"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# チェストを渡します．
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /chest:
    description:Give Chest with root table.
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        make player execute command "function shimashima:02_prepare"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# エメラルドを渡します.
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /emerald <number>:
    description:Give Emeralds
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        give arg-1 of emerald to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 鬼ごっこへ移行します.でもこれ別にこのプラグインと一緒じゃなくてよくね？
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /onigokko:
    description:Move Onigokko Mode
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        if {status} is not 0:
            message "&b[admin] &r鬼ごっこモードへの移行に失敗しました。サーバーをリロードしてください。" to player
            stop
        else:
            set {mode.onigokko} to "true"
            set {status} to 4
            loop all players:
                clear {sidebar.%loop-player%}
            execute console command "datapack disable ""file/ibuibu"""
            execute console command "datapack enable ""file/fillesces_tag_games"""
            execute console command "effect clear @a"
            broadcast "&b[運営] &r鬼ごっこモードへ移行しました。"
            message "&b[admin] &rサーバーをリロードすると終了します。" to player


