# ====================================================================================================================================================================================
#
# ===For User===   全ユーザーが実行可能
#
# ====================================================================================================================================================================================

# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# バージョン情報を提示します
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /ver:
    description:Show version now working
    trigger:
        message "&b&l>System &r現在のバージョンは &c%{ver}% &rです" to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# ゲーム中に意図的に全体チャットを使用します。
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /z <text>:
    description:ZE-NN-TYA
    trigger:
        broadcast "&7[-ZENNTYA-] &r<%player%> %arg-1%"



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# プレイヤーヘッドとチェストがもらえます。
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /rirogu:
    description:Give Player Head and Chest.
    trigger:
        if {gameStatus} is not 1:
            set slot 4 of player's inventory to 1 of skull of player named "&d右クリックでチェックポイントへTP"
            set slot 7 of player's inventory to a ender chest named "&dキャラ選択"
            set slot 8 of player's inventory to a chest named "&dチーム選択"
            play sound "block.note_block.bell" to player
        else:
            play sound "block.note_block.banjo" to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 謎解きの回答を送信します。
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /answer <text>:
    description:Answer question.
    trigger:
        if {count.ans.%player%} is 0:
            add 1 to {count.ans.%player%}
            if arg-1 is "0":
                broadcast "&6&l>謎解き &r%player% が謎解きをクリアしました！！おめでとう！！！！"
                play sound "ui.toast.challenge_complete" to player
            else:
                message "&6&l>謎解き &r残念不正解..." to player
                play sound "entity.villager.no" to player
        else:
            message "&6&l>謎解き &r回答出来るのは一試合につき一回までです" to player
            play sound "block.note_block.banjo" to player



# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# チームメンバーにTPします
# ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /tpa <player>:
    description:Teleport team player.
    trigger:
        if {playerJoined.%player%} is {playerJoined.%arg-1%}:
            teleport player to arg-1
            play sound "block.note_block.bell" to player
            message "&b&l>Game %arg-1%にテレポートしました" to player
        else:
            play sound "block.note_block.banjo" to player
            message "&b&l>Game &r無効なプレイヤーです"


command /openchest <player>:
    trigger:
        open chest inventory with 3 row to arg-1
        play sound "block.chest.open" to arg-1
        set {_random.chestSlotQua} to random integer between 1 and {Natto.maxChestSlotQua}
        loop {_random.chestSlotQua} times:
            set {_random.chestSlotNum} to random integer between 0 and 26
            if {mode.skill} is true:
                set {_random.itemNumber} to random integer between 1 and {Natto.qua.ChestItem.skill}
                set slot {_random.chestSlotNum} of arg-1's current inventory to {Natto.chestRoot.skill::%{_random.itemNumber}%}
            if {mode.yumi} is true:
                set {_random.itemNumber} to random integer between 1 and {Natto.qua.ChestItem.yumi}
                set slot {_random.chestSlotNum} of arg-1's current inventory to {Natto.chestRoot.yumi::%{_random.itemNumber}%}
            if {mode.yukidama} is true:
                set {_random.itemNumber} to random integer between 1 and {Natto.qua.ChestItem.yukidama}
                set slot {_random.chestSlotNum} of arg-1's current inventory to {Natto.chestRoot.yukidama::%{_random.itemNumber}%}
            else:
                set {_random.itemNumber} to random integer between 1 and {Natto.qua.ChestItem.normal}
                set slot {_random.chestSlotNum} of arg-1's current inventory to {Natto.chestRoot.normal::%{_random.itemNumber}%}

on right click on chest:
    set the clicked block to air
    execute console command "openchest %player%"