# ========================================================================================
#
# Config
#
function gameConfig():
# =======================================================================================
# ---------------------------------------------------------------------------------------
#
    # バージョン情報
    set {ver} to "4.3.1 (beta)"
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # デフォルトゲームモード
    #---------
    # チーム戦
    set {Natto.defaultModeTeam} to false
    #---------
    # 弓のみ
    set {Natto.defaultModeYumi} to false
    #---------
    # 雪玉のみ
    set {Natto.defaultModeYukidama} to false
    #---------
    # ibuibu Mode
    set {Natto.defaultModeIbuibu} to false
    # ---------
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 各チーム最大人数（３人以上はGUI非対応）
    set {Natto.teamMaxPlayer} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 開始前待機時間
    set {Natto.prepareTime} to 30
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # キルランキング表示順位数（上位〜位）
    set {Natto.KillRankingTimes} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # だるまモードでの被ダメージ量
    set {Natto.daruma.damage} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 回復薬での体力回復量
    set {Natto.oniku.healAmount} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 一つのチェストから出るアイテム量（チェストインベントリーにおけるスロット占有量）
    set {Natto.maxChestSlotQua} to 5
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チェスト中身(モード：ノーマル)
    # その確率
    #
    add potion named "回復薬" to {Natto.chestItemName.normal::*}
    add 20 to {Natto.chestItemChance.normal::*}
    #
    add cooked porkchop named "食糧" to {Natto.chestItemName.normal::*}
    add 20 to {Natto.chestItemChance.normal::*}
    #
    add 10 of emerald to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
    #
    add wooden sword to {Natto.chestItemName.normal::*}
    add 5 to {Natto.chestItemChance.normal::*}
    #
    add bow to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
    #
    add 10 of arrow to {Natto.chestItemName.normal::*}
    add 20 to {Natto.chestItemChance.normal::*}
    #
    add wooden axe to {Natto.chestItemName.normal::*}
    add 5 to {Natto.chestItemChance.normal::*}
    #
    add chaimmail chestplate to {Natto.chestItemName.normal::*} #FIXME:Skriptがエラー吐く
    add 3 to {Natto.chestItemChance.normal::*}
    #
    add chainmail helmet to {Natto.chestItemName.normal::*}
    add 3 to {Natto.chestItemChance.normal::*}
    #
    add leather chestplate to {Natto.chestItemName.normal::*}
    add 6 to {Natto.chestItemChance.normal::*}
    #
    add leather helmet to {Natto.chestItemName.normal::*}
    add 6 to {Natto.chestItemChance.normal::*}
    #
    add iron chestplate to {Natto.chestItemName.normal::*}
    add 1 to {Natto.chestItemChance.normal::*}
    #
    add iron helmet to {Natto.chestItemName.normal::*}
    add 1 to {Natto.chestItemChance.normal::*}
    #
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チェスト中身(モード：弓のみ)
    # その確率
    #
    add cooked beef to {Natto.chestItemName.yumi::*}
    add 60 to {Natto.chestItemChance.yumi::*}
    #
    add 5 of emerald to {Natto.chestItemName.yumi::*}
    add 40 to {Natto.chestItemChance.yumi::*}
    #
    add bow to {Natto.chestItemName.yumi::*}
    add 20 to {Natto.chestItemChance.yumi::*}
    #
    add 5 of arrow to {Natto.chestItemName.yumi::*}
    add 30 to {Natto.chestItemChance.yumi::*}
    #
    add wooden axe to {Natto.chestItemName.yumi::*}
    add 20 to {Natto.chestItemChance.yumi::*}
    #
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チェスト中身(モード：雪玉のみ)
    # その確率
    #
    add cooked beef to {Natto.chestItemName.yukidama::*}
    add 60 to {Natto.chestItemChance.yukidama::*}
    #
    add 5 of emerald to {Natto.chestItemName.yukidama::*}
    add 40 to {Natto.chestItemChance.yukidama::*}
    #
    add snowball to {Natto.chestItemName.yukidama::*}
    add 60 to {Natto.chestItemChance.yukidama::*}
    #
    add wooden axe to {Natto.chestItemName.yukidama::*}
    add 20 to {Natto.chestItemChance.yukidama::*}
    #
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チーム数・チーム名
    add "red" to {Natto.teamName::*}
    add "blue" to {Natto.teamName::*}
    add "yellow" to {Natto.teamName::*}
    add "green" to {Natto.teamName::*}
    add "orange" to {Natto.teamName::*}
    add "purple" to {Natto.teamName::*}
    add "black" to {Natto.teamName::*}
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # デバッグモード
    set {debugMode} to false
#
# ---------------------------------------------------------------------------------------