# ====================================================================================================================================================================================
#
# Config
#
function gameConfig():
# ====================================================================================================================================================================================
# ---------------------------------------------------------------------------------------
#
    # バージョン情報
    set {ver} to "4.2.0 (alpha)"
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # デフォルトゲームモード
    #---------
    # チーム戦
    set {Natto.defaultModeTeam} to false
    #---------
    # キャラ
    set {Natto.defaultModeSkill} to false
    #---------
    # 弓のみ
    set {Natto.defaultModeYumi} to false
    #---------
    # 雪玉のみ
    set {Natto.defaultModeYukidama} to false
    #---------
    # ibuibu Mode
    set {Natto.defaultModeIbuibu} to false
    # ---------
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 各チーム最大人数（３人以上はGUI非対応）
    set {Natto.teamMaxPlayer} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 開始前待機時間
    set {Natto.prepareTime} to 30
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # キルランキング表示順位数（上位〜位）
    set {Natto.KillRankingTimes} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # だるまモードでの被ダメージ量
    set {Natto.daruma.damage} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 回復薬での体力回復量
    set {Natto.oniku.healAmount} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 一つのチェストから出るアイテム量（チェストインベントリーにおけるスロット占有量）
    set {Natto.maxChestSlotQua} to 5
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チェスト中身(モード：ノーマル)
    # その確率
    #
    add potion named "回復薬" to {Natto.chestItemName.normal::*}
    add 20 to {Natto.chestItemChance.normal::*}
    #
    add cooked porkchop named "食糧" to {Natto.chestItemName.normal::*}
    add 20 to {Natto.chestItemChance.normal::*}
    #
    add 10 of emerald to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
    #
    add wooden sword to {Natto.chestItemName.normal::*}
    add 5 to {Natto.chestItemChance.normal::*}
    #
    add bow to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
    #
    add 10 of arrow to {Natto.chestItemName.normal::*}
    add 20 to {Natto.chestItemChance.normal::*}
    #
    add wooden axe to {Natto.chestItemName.normal::*}
    add 5 to {Natto.chestItemChance.normal::*}
    #
    add chaimmail chestplate to {Natto.chestItemName.normal::*} #FIXME:Skriptがエラー吐く
    add 3 to {Natto.chestItemChance.normal::*}
    #
    add chainmail helmet to {Natto.chestItemName.normal::*}
    add 3 to {Natto.chestItemChance.normal::*}
    #
    add leather chestplate to {Natto.chestItemName.normal::*}
    add 6 to {Natto.chestItemChance.normal::*}
    #
    add leather helmet to {Natto.chestItemName.normal::*}
    add 6 to {Natto.chestItemChance.normal::*}
    #
    add iron chestplate to {Natto.chestItemName.normal::*}
    add 1 to {Natto.chestItemChance.normal::*}
    #
    add iron helmet to {Natto.chestItemName.normal::*}
    add 1 to {Natto.chestItemChance.normal::*}
    #
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チェスト中身(モード：弓のみ)
    # その確率
    #
    add cooked beef to {Natto.chestItemName.yumi::*}
    add 60 to {Natto.chestItemChance.yumi::*}
    #
    add 5 of emerald to {Natto.chestItemName.yumi::*}
    add 40 to {Natto.chestItemChance.yumi::*}
    #
    add bow to {Natto.chestItemName.yumi::*}
    add 20 to {Natto.chestItemChance.yumi::*}
    #
    add 5 of arrow to {Natto.chestItemName.yumi::*}
    add 30 to {Natto.chestItemChance.yumi::*}
    #
    add wooden axe to {Natto.chestItemName.yumi::*}
    add 20 to {Natto.chestItemChance.yumi::*}
    #
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チェスト中身(モード：雪玉のみ)
    # その確率
    #
    add cooked beef to {Natto.chestItemName.yukidama::*}
    add 60 to {Natto.chestItemChance.yukidama::*}
    #
    add 5 of emerald to {Natto.chestItemName.yukidama::*}
    add 40 to {Natto.chestItemChance.yukidama::*}
    #
    add snowball to {Natto.chestItemName.yukidama::*}
    add 60 to {Natto.chestItemChance.yukidama::*}
    #
    add wooden axe to {Natto.chestItemName.yukidama::*}
    add 20 to {Natto.chestItemChance.yukidama::*}
    #
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チェスト中身(モード：キャラあり)
    # その確率
    #
    add cooked beef to {Natto.chestItemName.skill::*}
    add 60 to {Natto.chestItemChance.skill::*}
    #
    add 5 of emerald to {Natto.chestItemName.skill::*}
    add 40 to {Natto.chestItemChance.skill::*}
    #
    add bow to {Natto.chestItemName.skill::*}
    add 20 to {Natto.chestItemChance.skill::*}
    #
    add 5 of arrow to {Natto.chestItemName.skill::*}
    add 30 to {Natto.chestItemChance.skill::*}
    #
    add wooden axe to {Natto.chestItemName.skill::*}
    add 20 to {Natto.chestItemChance.skill::*}
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チーム数・チーム名
    add "red" to {Natto.teamName::*}
    add "blue" to {Natto.teamName::*}
    add "yellow" to {Natto.teamName::*}
    add "green" to {Natto.teamName::*}
    add "orange" to {Natto.teamName::*}
    add "purple" to {Natto.teamName::*}
    add "black" to {Natto.teamName::*}
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # キャラ数・キャラ名
    set {Natto.charaName::1} to "ninja"
    set {Natto.charaName::2} to "gorilla"
    set {Natto.charaName::3} to "healer"
    set {Natto.charaName::4} to "neet"
    set {Natto.charaName::5} to "tyuuni"
    set {Natto.charaName::6} to "tank"
    set {Natto.charaName::7} to "robot"
#
# ---------------------------------------------------------------------------------------
# 以下各キャラのパラメータ.
# ※体力について、ディスコの体力の値を２で割って定義すること
# ---------------------------------------------------------------------------------------
#
    # 忍者
    #
    # ---------
    # クールタイム-瞬間移動
    set {Natto.cooltime.ender} to 15
    # ---------
    # クールタイム-かくれみの術
    set {Natto.cooltime.invisible} to 30
    # ---------
    # アイテム-瞬間移動
    set {Natto.skill.ender} to ender pearl named "&r&5瞬間移動" with lore "&r&f投げて使用" and "&r&bクールタイム：%{Natto.cooltime.ender}%秒"
    # ---------
    # アイテム-かくれみの術
    set {Natto.skill.invisible} to sunflower named "&r&5かくれみの術" with lore "&r&f右クリックで10秒間透明" and "&r&bクールタイム：%{Natto.cooltime.invisible}%秒"
    # ---------
    # レベル別装備
    set {Natto.weapon.ninja.1} to wooden sword
    set {Natto.weapon.ninja.2} to stone sword
    set {Natto.weapon.ninja.3} to iron sword
    # ---------
    # レベル別最大体力
    set {Natto.maxHealth.ninja.1} to 5
    set {Natto.maxHealth.ninja.2} to 7
    set {Natto.maxHealth.ninja.3} to 10
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # ゴリラ
    #
    # ---------
    # クールタイム-爆風
    set {Natto.cooltime.explo} to 30
    # ---------
    # クールタイム-ドラミング
    set {Natto.cooltime.drumming} to 30
    # ---------
    # アイテム-爆風
    set {Natto.skill.explo} to fire charge named "&r&5爆風" with lore "&r&f右クリックで爆風を起こす" and "&r&bクールタイム：%{Natto.cooltime.explo}%秒"
    # ---------
    # アイテム-ドラミング
    set {Natto.skill.drumming} to composter named "&r&5ドラミング" with lore "&r&f10秒間シフトでドラミングする" and "&r&bクールタイム：%{Natto.cooltime.drumming}%秒"
    # ---------
    # レベル別装備
    set {Natto.weapon.gorilla.1} to iron sword
    set {Natto.weapon.gorilla.2} to golden sword
    set {Natto.weapon.gorilla.3} to diamond sword
    # ---------
    # レベル別最大体力
    set {Natto.maxHealth.gorilla.1} to 10
    set {Natto.maxHealth.gorilla.2} to 15
    set {Natto.maxHealth.gorilla.3} to 20
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # ヒーラー
    #
    # ---------
    # クールタイム-ヒール
    set {Natto.cooltime.heal} to 10
    # ---------
    # クールタイム-無敵
    set {Natto.cooltime.resistance} to 60
    # ---------
    # アイテム-ヒール
    set {Natto.skill.heal} to nether star named "&r&5ヒール" with lore "&r&fシフトで味方を回復" and "&r&bクールタイム：%{Natto.cooltime.heal}%秒"
    # ---------
    # アイテム-無敵
    set {Natto.skill.resistance} to end crystal named "&r&5無敵" with lore "&r&f右クリックで10秒間無敵" and "&r&bクールタイム：%{Natto.cooltime.resistance}%秒"
    # ---------
    # "ヒール"回復量
    set {Natto.skill.heal.healAmount} to 2
    # ---------
    # レベル別装備
    set {Natto.weapon.healer.1} to wooden sword
    set {Natto.weapon.healer.2} to stone sword
    set {Natto.weapon.healer.3} to stone sword
    # ---------
    # レベル別最大体力
    set {Natto.maxHealth.healer.1} to 20
    set {Natto.maxHealth.healer.2} to 12
    set {Natto.maxHealth.healer.3} to 15
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 厨二病
    #
    # ---------
    # クールタイム-チャージ
    set {Natto.cooltime.charge} to 10
    # ---------
    # クールタイム-右手
    set {Natto.cooltime.migite} to 100
    # ---------
    # アイテム-チャージ
    set {Natto.skill.charge} to chorus plant named "&r&5チャージ" with lore "&r&fシフトでチャージする" and "&r&f10回チャージで覚醒" and "&r&bクールタイム：%{Natto.cooltime.charge}%秒"
    # ---------
    # アイテム-右手（前）
    set {Natto.skill.migite.mae} to dragon head named "&r&5ɫ封印されし我が右手いまこそ解き放てɫ" with lore "&r&f覚醒後に使用可能" and "&r&f相手を一撃で倒せる" and "&r&bクールタイム：%{Natto.cooltime.migite}%秒"
    # ---------
    # アイテム-右手（後）
    set {Natto.skill.migite.ato} to dragon head named "&r&5ɫ封印されし我が右手いまこそ解き放てɫ" with lore "&r&f相手を一撃で倒せる" and "&r&bクールタイム：%{Natto.cooltime.migite}%秒"
    # ---------
    # 覚醒前後装備
    set {Natto.weapon.tyuuni.1} to wooden sword
    set {Natto.weapon.tyuuni.2} to diamond sword
    # ---------
    # 覚醒前後最大体力
    set {Natto.maxHealth.tyuuni.1} to 5
    set {Natto.maxHealth.tyuuni.2} to 30
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # タンク
    #
    # ---------
    # クールタイム-バリアー
    set {Natto.cooltime.barrier} to 20
    # ---------
    # クールタイム-プロテクト
    set {Natto.cooltime.protect} to 30
    # ---------
    # アイテム-バリアー
    set {Natto.skill.barrier} to glass named "&r&5バリアー" with lore "&r&fシフトで自分中心にバリアーをはる" and "&r&bクールタイム：%{Natto.cooltime.barrier}%秒"
    # ---------
    # アイテム-プロテクト
    set {Natto.skill.protect} to anvil named "&r&5プロテクト" with lore "&r&f右クリックで味方の防御力を上げる" and "&r&bクールタイム：%{Natto.cooltime.protect}%秒"
    # ---------
    # "バリアー"壁の半径
    set {Natto.skill.barrier.distance} to 5
    # ---------
    # レベル別装備
    set {Natto.weapon.tank.1} to stone sword
    set {Natto.weapon.tank.2} to stone sword
    set {Natto.weapon.tank.3} to iron sword
    # ---------
    # レベル別最大体力
    set {Natto.maxHealth.tank.1} to 20
    set {Natto.maxHealth.tank.2} to 30
    set {Natto.maxHealth.tank.3} to 40
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # ロボット
    #
    # ---------
    # クールタイム-グレネード
    set {Natto.cooltime.grappling} to 15
    # ---------
    # クールタイム-グラップリングフック
    set {Natto.cooltime.snowball} to 10
    # ---------
    # アイテム-グレネード
    set {Natto.skill.grappling} to snowball named "&r&5グレネード" with lore "&r&f右クリックで投擲" and "&r&bクールタイム：%{Natto.cooltime.grappling}%秒"
    # ---------
    # アイテム-グラップリングフック
    set {Natto.skill.snowball} to fishing rod named "&r&5グラップリングフック" with lore "&r&f右クリックで投擲" and "&r&bクールタイム：%{Natto.cooltime.snowball}%秒"
    # ---------
    # "グレネード"爆破威力
    set {Natto.skill.snowball.power} to 1
    # ---------
    # レベル別装備
    set {Natto.weapon.robot.1} to stone sword
    set {Natto.weapon.robot.2} to iron sword
    set {Natto.weapon.robot.3} to golden sword
    # ---------
    # レベル別最大体力
    set {Natto.maxHealth.robot.1} to 10
    set {Natto.maxHealth.robot.2} to 15
    set {Natto.maxHealth.robot.3} to 20
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # ニート
    #
    # ---------
    # レベル別装備
    set {Natto.weapon.neet.1} to wooden sword
    set {Natto.weapon.neet.2} to wooden sword
    set {Natto.weapon.neet.3} to golden sword
    # ---------
    # レベル別最大体力
    set {Natto.maxHealth.neet.1} to 5
    set {Natto.maxHealth.neet.2} to 5
    set {Natto.maxHealth.neet.3} to 20
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # デバッグモード
    set {debugMode} to false
#
# ---------------------------------------------------------------------------------------