# =======================================================================================
#
# Config
#
function gameConfig():
# =======================================================================================
# ---------------------------------------------------------------------------------------
#
    # バージョン情報
    set {ver} to "4.5.2"
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # デフォルトゲームモード
    #---------
    # チーム戦
    set {Natto.defaultModeTeam} to false
    #---------
    # だるま
    set {Natto.defaultModeDaruma} to false
    #---------
    # ibuibu Mode
    set {Natto.defaultModeIbuibu} to false
    # ---------
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 各チーム最大人数（３人以上はGUI非対応）
    set {Natto.teamMaxPlayer} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 開始前待機時間
    set {Natto.prepareTime} to 30
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # キルランキング表示順位数（上位〜位）
    set {Natto.KillRankingTimes} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # だるまモードでの被ダメージ量
    set {Natto.daruma.damage} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 回復薬での体力回復量
    set {Natto.oniku.healAmount} to 3
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # 一つのチェストから出るアイテム量（チェストインベントリーにおけるスロット占有量）
    set {Natto.maxChestSlotQua} to 10
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # ブロック設置後消えるまでの時間（秒）
    set {Natto.delBlockTime} to 60
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チェスト中身(モード：ノーマル)
    # その確率
    #
    add 3 of apple to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
    #
    add 2 of firework rocket to {Natto.chestItemName.normal::*}
    add 5 to {Natto.chestItemChance.normal::*}
    #
    add 3 of emerald to {Natto.chestItemName.normal::*}
    add 5 to {Natto.chestItemChance.normal::*}
    #
    add 3 of lapis lazuli to {Natto.chestItemName.normal::*}
    add 2 to {Natto.chestItemChance.normal::*}
    #
    add 10 of experience bottle to {Natto.chestItemName.normal::*}
    add 3 to {Natto.chestItemChance.normal::*}
    #
    add 2 of oak log to {Natto.chestItemName.normal::*}
    add 15 to {Natto.chestItemChance.normal::*}
    #
    add 2 of stone to {Natto.chestItemName.normal::*}
    add 15 to {Natto.chestItemChance.normal::*}
    #
    add 2 of string to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
    #
    add 5 of arrow to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
    #
    add 3 of leather to {Natto.chestItemName.normal::*}
    add 10 to {Natto.chestItemChance.normal::*}
    #
    add 3 of iron ingot to {Natto.chestItemName.normal::*}
    add 8 to {Natto.chestItemChance.normal::*}
    #
    add 3 of gold ingot to {Natto.chestItemName.normal::*}
    add 5 to {Natto.chestItemChance.normal::*}
    #
    add 1 of diamond to {Natto.chestItemName.normal::*}
    add 2 to {Natto.chestItemChance.normal::*}
    #
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # チーム数・チーム名
    add "red" to {Natto.teamName::*}
    add "blue" to {Natto.teamName::*}
    add "yellow" to {Natto.teamName::*}
    add "green" to {Natto.teamName::*}
    add "orange" to {Natto.teamName::*}
    add "purple" to {Natto.teamName::*}
    add "black" to {Natto.teamName::*}
#
# ---------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------
#
    # デバッグモード
    set {debugMode} to false
#
# ---------------------------------------------------------------------------------------