# ===============================================================================================================================================================================================
# 開発用コマンド
# 基本使わないコマンド群 -> 頭にnattoつけて差別化
# ===============================================================================================================================================================================================

# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 開発モードに移行します.
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /dev:
    description:Move to Development Mode
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        broadcast "&b[admin] &r開発モードに移行します.終了する際はリロードしてください."
        execute console command "destroyable true"
        execute console command "gamerule sendCommandFeedback true"
        execute console command "gamerule reducedDebugInfo false"
        set {status} to 0
        loop all players:
            set loop-player's gamemode to creative



# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# LuckPermsの初期設定を行います．
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /nattorakutinlp:
    description:Create group on LuckPerms
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        execute console command "lp user ShimaShima_710 permission set luckperms.*"
        make player execute command "/lp creategroup player"
        make player execute command "/lp creategroup skript.admin"
        make player execute command "/lp group skript.admin permission set skript.* true"
        make player execute command "/lp user ShimaShima_710 parent add skript.admin"
        message "&e[RakutinLP] &r正常に実行されました" to player



# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# LuckPermsにおける各権限グループのメンバーを表示します．
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /nattorakutinlpmember:
    description:Show LuckPerms members
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        make player execute command "/lp group skript.admin listmembers"
        make player execute command "/lp group player listmembers"
        message "&e[RakutinLP Member] &r正常に実行されました" to player






# ===============================================================================================================================================================================================
# ===Legacy System===  すでに更新を終えているため動作はサポートされません
# ===============================================================================================================================================================================================

# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 変数・スコアのリセットをします．現在はリロードに組み込んであるので不要です．
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /nattodebug:
    description:Reset variable via Skript and scores via Datapack
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        make player execute command "/admin leave"
        set {surviver} to 0
        set {qua.admin} to 0
        set {qua.player} to 0
        execute console command "function shimashima:01_replay"



# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# CoreProtectでワールドのロールバックをします．動きませんでしたがは
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /nattoreset:
    description:Test for CoreProtect *not adopted
    permission: skript.admin
    permission message:Admin専用コマンドです。
    trigger:
        loop all players:
            execute console command "co rollback time: 1d radius: ##world user:%loop-player%"