# ===============================================================================================================================================================================================
# every x 〜
# 毎〜実行はここ
# ==============================================================================================================================================================================================


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# {sidebar.%player%}について
# 0 -> ゲーム外＜廃止＞
# 1 -> ゲーム中（生存）
# 2 -> ゲーム中（死亡）
# 9 -> ゲームマスター＜廃止＞
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# {status}について
# 0 -> 開始前
# 1 -> ゲーム中
# 2 -> ゲーム終了後
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------


# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 毎秒実行.内容説明は長いので下に．
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
every 1 second:
    if {surviver} is 1:
        execute console command "game end"
        set {status} to 2
        set {surviver} to 0
        set {rank.alive} to 1
    loop all players:
        set {emerald.%loop-player%} to amount of emerald in loop-player's inventory
        wipe loop-player's sidebar
        set name of sidebar of loop-player to "&l%loop-player's name%"
        if {status} is 0:
            set score "&a状態      &r: 準備中" in sidebar of loop-player to 0
            set score "しばらくお待ちください" in sidebar of loop-player to -1
        if {sidebar.%loop-player%} is 1:
            set score "&a状態      &r: 生存" in sidebar of loop-player to 0
            set score "&a残り人数  &r: %{surviver}%人" in sidebar of loop-player to -1
            set score "&a==============" in sidebar of loop-player to -2
            set score "&a順位      &r: %{rank.alive}%位" in sidebar of loop-player to -3
            set score "&aキル数    &r: %{kills.%loop-player%}%人" in sidebar of loop-player to -4
            set score "&aエメラルド  &r: %{emerald.%loop-player%}%個" in sidebar of loop-player to -5
        if {sidebar.%loop-player%} is 2:
            set score "&a状態      &r: 死亡" in sidebar of loop-player to 0
            set score "&a残り人数  &r: %{surviver}%人" in sidebar of loop-player to -1
            set score "&a==============" in sidebar of loop-player to -2
            set score "&a順位      &r: %{rank.%loop-player%}%位" in sidebar of loop-player to -3
            set score "&aキル数    &r: %{kills.%loop-player%}%人" in sidebar of loop-player to -4
        if {admin.%loop-player%} is "true":
            set score "&a状態      &r: 非参加" in sidebar of loop-player to 1
            set score "&a==========================" in sidebar of loop-player to -90
            set score "&astatus     &r: &cadmin" in sidebar of loop-player to -91
            set score "&aonline     &r: %online player count%人" in sidebar of loop-player to -92
            set score "&aqua.player &r: %{qua.player}%人" in sidebar of loop-player to -93
            set score "&aqua.admin  &r: %{qua.admin}%人" in sidebar of loop-player to -94
            set score "&adestroyable&r: %{destroyable}%" in sidebar of loop-player to -95
            

# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# 上から
#   もし残り人数が一人だったら
#       ゲームを終了・{status}を2・残り人数を0・生存者の順位を1位にする
#   {status}=0 (開始前)
#       おまち状態
#   {sidebar.%player%}=1 (生存)
#       生きとるで状態
#   {sidebar.%player%}=2 (死亡)
#       死んじゃった状態
#   {admin.%player%}=true (admin)
#       adminでっす状態
# ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------